//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSourceControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Art()
        {
            this.VirtualGallery = new HashSet<VirtualGallery>();
        }
    
        public int ArtPieceID { get; set; }
        public string Title { get; set; }
        public System.DateTime DateDisplayed { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateAvailableForSale { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Style { get; set; }
        public bool IsInteractive { get; set; }
        public string TargetedAgeRange { get; set; }
        public string Description { get; set; }
        public string ArtURL { get; set; }
    
        public virtual ArtLocation ArtLocation { get; set; }
        public virtual DisplayedArtistPieces DisplayedArtistPieces { get; set; }
        public virtual MediaUsed MediaUsed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VirtualGallery> VirtualGallery { get; set; }
    }
}
