//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSourceControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artists()
        {
            this.DisplayedArtistPieces = new HashSet<DisplayedArtistPieces>();
            this.MediaUsed = new HashSet<MediaUsed>();
            this.OtherGalleryWorks = new HashSet<OtherGalleryWorks>();
        }
    
        public int ArtistID { get; set; }
        public string ArtistFirstName { get; set; }
        public string ArtistLastName { get; set; }
        public string ArtistTag { get; set; }
        public string ArtistEmail { get; set; }
        public string ArtistPhone { get; set; }
        public string ArtistCity { get; set; }
        public string ArtistState { get; set; }
        public string AboutTheArtist { get; set; }
        public string ArtistWebsite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisplayedArtistPieces> DisplayedArtistPieces { get; set; }
        public virtual FeaturedArtists FeaturedArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaUsed> MediaUsed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherGalleryWorks> OtherGalleryWorks { get; set; }
    }
}
