//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSourceControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtLocation
    {
        public int ArtPieceID { get; set; }
        public string HallNumber { get; set; }
        public string RoomNumber { get; set; }
        public string SpaceNumber { get; set; }
    
        public virtual Art Art { get; set; }
    }
}
