//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSourceControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayedArtistPieces
    {
        public int ArtistPieceID { get; set; }
        public Nullable<int> ArtistID { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual Artists Artists { get; set; }
    }
}
