//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSourceControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CtrlArtGalleryEntities : DbContext
    {
        public CtrlArtGalleryEntities()
            : base("name=CtrlArtGalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Art> Art { get; set; }
        public virtual DbSet<ArtistMedia> ArtistMedia { get; set; }
        public virtual DbSet<Artists> Artists { get; set; }
        public virtual DbSet<ArtLocation> ArtLocation { get; set; }
        public virtual DbSet<DisplayedArtistPieces> DisplayedArtistPieces { get; set; }
        public virtual DbSet<FeaturedArtists> FeaturedArtists { get; set; }
        public virtual DbSet<GalleryEvents> GalleryEvents { get; set; }
        public virtual DbSet<GalleryInfo> GalleryInfo { get; set; }
        public virtual DbSet<GalleryVisitors> GalleryVisitors { get; set; }
        public virtual DbSet<MediaUsed> MediaUsed { get; set; }
        public virtual DbSet<OtherGalleryWorks> OtherGalleryWorks { get; set; }
        public virtual DbSet<VirtualGallery> VirtualGallery { get; set; }
    }
}
